CATALOG:
  SDSS16: {id: V/154, ra: RA_ICRS, dec: DE_ICRS, source_id: fieldID,
  obj_id: objID, g: gmag, u: umag, r: rmag, i: imag, z: zmag, filter: {gmag: <21},
  flag: 'gmag'}

  2MASS: {id: II/246/out, source_id: _2MASS, ra: RAJ2000, dec: DEJ2000,
  h: Hmag, j: Jmag, k: Kmag, b: Bmag, r: Rmag, filter: {Hmag: <15}, flag: Hmag}

  2MASS_6X: {id: II/281/2mass6x, source_id: _2MASS, ra: RAJ2000, dec: DEJ2000, h: Hmag, j: Jmag,
  k: Kmag, b: Bmag, r: Rmag, filter: {Hmag: <30}, flag: Hmag}

BG_FOV: 8

INSTRUMENT:
  FORS2_std: 7.1
  FORS2_hres: 4.25
  MUSE_wfm: 1
  MUSE_nfm: 0.125
  HAWK-I: 7.5

HIPS_SURVEY:
  DSS2red: CDS/P/DSS2/red
  DSS2blue: CDS/P/DSS2/blue
  SDSSg: CDS/P/SDSS9/g
  SDSSr: CDS/P/SDSS9/r
  SDSSz: CDS/P/SDSS9/z
  2MASSh: CDS/P/2MASS/H
  2MASSj: CDS/P/2MASS/J
  2MASSk: CDS/P/2MASS/K
  2MASS6X_h: CDS/P/2MASS6X/H
  2MASS6X_j: CDS/P/2MASS6X/J
  2MASS6X_k: CDS/P/2MASS6X/K

OB_PATH: OB_format

NUM_RESULTS: '100'

T_SCALE:
  UTC: 'utc'
  UT1: 'ut1'
  LST: 'lst'

